apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice 
  labels:
    app: payment
spec:
  replicas: 3
  selector:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: server
        image: interpris/paymentservice:v0.0.2

